#!/bin/sh -e

. /usr/share/debconf/confmodule

#set -v -x; DEBIAN_SCRIPT_TRACE=1;
#if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
#${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }

# only ask this question on fresh installs, during "reconfiguration" and when 
# not upgrading from an existing 5.0 installation.
# there is also an additional check for empty root passwords in the
# postinst script when the tools are available for us to use.

get_password()
{
	question=$1
	while :; do
		RET=""
		db_input high master-slave-detector/$question || true
		db_go
		db_get master-slave-detector/$question
		# if password isn't empty we ask for password verification
		if [ -z "$RET" ]; then
			db_fset master-slave-detector/$question seen false
			db_fset master-slave-detector/${question}-again seen false
			break
		fi
		ROOT_PW="$RET"
		db_input high master-slave-detector/${question}-again || true
		db_go
		db_get master-slave-detector/${question}-again
		if [ "$RET" = "$ROOT_PW" ]; then
			ROOT_PW=''
			break
		fi
		db_fset master-slave-detector/password-mismatch seen false
		db_input critical master-slave-detector/password-mismatch
		db_set master-slave-detector/$question "" 
		db_set master-slave-detector/${question}-again ""
		db_go
	done
}


if [ "$1" = "configure" ] && [ -z "$2" ] || [ "$1" = "reconfigure" ]
then
	get_password cookie
#	db_input high master-slave-detector/nodename || true
#	db_go
#	db_input high master-slave-detector/hostname || true
#	db_go
	db_input high master-slave-detector/nodeset || true
	db_go
fi
