Document: master-slave-detector
Title: Debian master-slave-detector Manual
Author: <insert document author here>
Abstract: This manual describes what master-slave-detector is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/master-slave-detector/master-slave-detector.sgml.gz

Format: postscript
Files: /usr/share/doc/master-slave-detector/master-slave-detector.ps.gz

Format: text
Files: /usr/share/doc/master-slave-detector/master-slave-detector.text.gz

Format: HTML
Index: /usr/share/doc/master-slave-detector/html/index.html
Files: /usr/share/doc/master-slave-detector/html/*.html
