#!/bin/sh
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et

RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd)

RUNNER_BASE_DIR=${RUNNER_SCRIPT_DIR%/*}
RUNNER_ETC_DIR=/etc/msdetector
RUNNER_LOG_DIR=/var/log/msdetector
# Note the trailing slash on $PIPE_DIR/
PIPE_DIR=/tmp/$RUNNER_BASE_DIR/
RUNNER_USER=

# Make sure this script is running as the appropriate user
if [ ! -z "$RUNNER_USER" ] && [ `whoami` != "$RUNNER_USER" ]; then
exec sudo -u $RUNNER_USER -i $0 $@
fi

# Make sure CWD is set to runner base dir
cd $RUNNER_BASE_DIR

# Make sure log directory exists
mkdir -p $RUNNER_LOG_DIR
# Identify the script name
SCRIPT=`basename $0`

# Parse out release and erts info
START_ERL=`cat $RUNNER_BASE_DIR/releases/start_erl.data`
ERTS_VSN=${START_ERL% *}
APP_VSN=${START_ERL#* }

VMARGS_PATH="$RUNNER_ETC_DIR/vm.args"

CONFIG_PATH="$RUNNER_ETC_DIR/app.config"

# Extract the target node name from node.args
NAME_ARG=`egrep '^-s?name' $VMARGS_PATH`
if [ -z "$NAME_ARG" ]; then
echo "vm.args needs to have either -name or -sname parameter."
    exit 1
fi

# Extract the target cookie
COOKIE_ARG=`grep '^-setcookie' $VMARGS_PATH`
if [ -z "$COOKIE_ARG" ]; then
echo "vm.args needs to have a -setcookie parameter."
    exit 1
fi

# Add ERTS bin dir to our path
ERTS_PATH=$RUNNER_BASE_DIR/erts-$ERTS_VSN/bin

# Setup command to control the node
NODETOOL="$ERTS_PATH/escript $ERTS_PATH/nodetool $NAME_ARG $COOKIE_ARG"

# Check the first argument for instructions
case "$1" in
    start)
        # Make sure there is not already a node running
        RES=`$NODETOOL ping`
        if [ "$RES" = "pong" ]; then
echo "Node is already running!"
            exit 1
        fi
HEART_COMMAND="$RUNNER_BASE_DIR/bin/$SCRIPT start"
        export HEART_COMMAND
        mkdir -p $PIPE_DIR
        shift # remove $1
        $ERTS_PATH/run_erl -daemon $PIPE_DIR $RUNNER_LOG_DIR "exec $RUNNER_BASE_DIR/bin/$SCRIPT console $@" 2>&1
        ;;

    stop)
        # Wait for the node to completely stop...
        PID=`ps ax -o pid= -o command=|\
        grep "$RUNNER_BASE_DIR/.*/[b]eam"|awk '{print $1}'`
        if [ "$PID" = "" ]
        then
echo "Daemon is stopped"
            exit 0
        fi;
        $NODETOOL stop
        ES=$?
        if [ "$ES" -ne 0 ]; then
exit $ES
        fi
while `kill -0 $PID 2>/dev/null`;
        do
sleep 1
        done
        ;;

    restart)
        ## Restart the VM without exiting the process
        $NODETOOL restart
        ES=$?
        if [ "$ES" -ne 0 ]; then
exit $ES
        fi
        ;;

    reboot)
        ## Restart the VM completely (uses heart to restart it)
        $NODETOOL reboot
        ES=$?
        if [ "$ES" -ne 0 ]; then
exit $ES
        fi
        ;;

    ping)
        ## See if the VM is alive
        $NODETOOL ping
        ES=$?
        if [ "$ES" -ne 0 ]; then
exit $ES
        fi
        ;;

    who_am_i)
        ## See if the VM is alive
        $NODETOOL rpcterms master who_am_i ""
        ES=$?
        if [ "$ES" -ne 0 ]; then
exit $ES
        fi
        ;;

    who_is_master)
        ## See if the VM is alive
        $NODETOOL rpcterms master who_is_master ""
        ES=$?
        if [ "$ES" -ne 0 ]; then
            exit $ES
        fi
        ;;

    who_is_slaves)
        ## See if the VM is alive
        $NODETOOL rpcterms master who_is_slaves ""
        ES=$?
        if [ "$ES" -ne 0 ]; then
            exit $ES
        fi
        ;;

    who_is_live)
        ## See if the VM is alive
        $NODETOOL rpcterms master who_is_live ""
        ES=$?
        if [ "$ES" -ne 0 ]; then
            exit $ES
        fi
        ;;

    who_is_dead)
        ## See if the VM is alive
        $NODETOOL rpcterms master who_is_dead ""
        ES=$?
        if [ "$ES" -ne 0 ]; then
            exit $ES
        fi
        ;;

    cluster_status)
        ## See if the VM is alive
        $NODETOOL rpcterms master cluster_status ""
        ES=$?
        if [ "$ES" -ne 0 ]; then
            exit $ES
        fi
        ;;

	connect) 
		if [ $# -ne 2 ] ; then
			echo "USAGE: master connect master@examle.org"
			exit 1
		fi
		$NODETOOL rpcterms master connect \'$2\'.
        ES=$?
        if [ "$ES" -ne 0 ]; then
            exit $ES
        fi
        ;;


    attach)
        # Make sure a node IS running
        RES=`$NODETOOL ping`
        ES=$?
        if [ "$ES" -ne 0 ]; then
echo "Node is not running!"
            exit $ES
        fi

shift
exec $ERTS_PATH/to_erl $PIPE_DIR
        ;;

    console|console_clean)
        # .boot file typically just $SCRIPT (ie, the app name)
        # however, for debugging, sometimes start_clean.boot is useful:
        case "$1" in
            console) BOOTFILE=$SCRIPT ;;
            console_clean) BOOTFILE=start_clean ;;
        esac
        # Setup beam-required vars
        ROOTDIR=$RUNNER_BASE_DIR
        BINDIR=$ROOTDIR/erts-$ERTS_VSN/bin
        EMU=beam
        PROGNAME=`echo $0 | sed 's/.*\\///'`
        CMD="$BINDIR/erlexec -boot $RUNNER_BASE_DIR/releases/$APP_VSN/$BOOTFILE -mode embedded -config $CONFIG_PATH -args_file $VMARGS_PATH -- ${1+"$@"}"
        export EMU
        export ROOTDIR
        export BINDIR
        export PROGNAME

        # Dump environment info for logging purposes
        echo "Exec: $CMD"
        echo "Root: $ROOTDIR"

        # Log the startup
        logger -t "$SCRIPT[$$]" "Starting up"

        # Start the VM
        exec $CMD
        ;;

    *)
        echo "Usage: $SCRIPT {start|stop|restart|reboot|ping|console|console_clean|attach}"
        echo "$SCRIPT {who_am_i|who_is_master|who_is_slaves|who_is_live|who_is_dead|cluster_status|connect NODE}"
        exit 1
        ;;
esac

exit 0
